databases:
  - name: musiikkidb
    plan: free
    databaseName: musiikki
    user: nurmi

services:
  - type: web
    plan: free
    name: musiikki
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn musiikki.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: musiikkidb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SUPERUSER_USERNAME
        value: "nurmi"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "nurmi123"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "jani.nurminen2@student.careeria.fi"