# Generated by Django 5.0.8 on 2024-08-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='band',
            name='year',
            field=models.IntegerField(),
        ),
    ]
